--[[
    SentinelAC canary  (auto-generated by sentinel_ac - do not edit; removed with /ac instrument remove)

    Loaded FIRST inside this resource's client VM. Wraps sensitive globals and reports every call that
    - originates from code that is not one of this resource's own script files (injected chunk), or
    - uses a server event / function this resource's client code never uses.
    When the server authorizes it (Config.Instrument.BlockInjectCalls) and the verdict is certain, the
    injected call is BLOCKED before it executes - the event/function never runs, so an injected event
    cannot take any effect. Everything else stays report-only; the server (sentinel_ac) re-validates
    every report against its own static scan before acting. Nothing on the player's machine is inspected.
]]

local AC_RESOURCE = "__AC_RESOURCE__"
local CANARY_FILE = "__CANARY_FILE__"
local HEARTBEAT   = __HEARTBEAT__
local WRAP        = { __WRAPPED__ }

local RESOURCE   = getResourceName(getThisResource())
local originals  = {}
local baseline   = nil
local queue      = {}
local counts     = {}
local flushTimer = nil
local hasDebug   = type(debug) == "table" and type(debug.getinfo) == "function"

local rawTrigger             = triggerServerEvent
local rawGetResourceFromName = getResourceFromName
local rawSetTimer            = setTimer
local rawIsTimer             = isTimer
local rawKillTimer           = killTimer
local rawOutputDebug         = outputDebugString

local NAMED = {
    triggerServerEvent = true, triggerLatentServerEvent = true, triggerEvent = true,
    addEvent = true, addEventHandler = true,
}

local function acAvailable()
    return rawGetResourceFromName(AC_RESOURCE) ~= false
end

local function normalise(s)
    if type(s) ~= "string" then return "?" end
    s = string.lower(s)
    s = string.gsub(s, "\\", "/")
    if string.sub(s, 1, 1) == "@" then s = string.sub(s, 2) end
    return s
end

-- level 1 = this function, 2 = wrapper, 3+ = real caller.
-- Skips C frames (pcall, sort callbacks) and tail-call frames (`return triggerServerEvent(...)` erases the
-- caller frame and leaves a pseudo frame whose source is "=(tail call)"). Returns nil when no real Lua
-- frame is visible; nil is never judged.
local function callerSource()
    if not hasDebug then return nil end
    for level = 3, 9 do
        local info = debug.getinfo(level, "S")
        if not info then return nil end
        local what = info.what
        local src  = info.source or "?"
        if what ~= "C" and what ~= "tail" and src ~= "=[C]" and src ~= "[C]" and src ~= "=(tail call)" and src ~= "?" and src ~= "=?" then
            return normalise(src)
        end
    end
    return nil
end

local function sourceKnown(src)
    if not src then return true end
    for _, f in ipairs(baseline.files) do
        if src == f or string.sub(src, -(#f + 1)) == "/" .. f then
            return true
        end
    end
    return false
end

local function flush()
    if not acAvailable() then
        queue = {}
        return
    end
    rawTrigger("SentinelAC:server:canary", localPlayer, RESOURCE, { items = queue, counts = counts, tick = getTickCount() })
    queue = {}
end

local function report(kind, fnName, name, src, blocked)
    local item = { k = kind, f = fnName, n = name, s = src }
    if blocked then item.blocked = true end
    queue[#queue + 1] = item
    if #queue >= 10 then flush() end
end

-- Pre-execution blocking decision. Must mirror the server's Instrument.confirm() exactly, but on the
-- "certain" side only: a call is blocked when the server would CONFIRM the report, never when it would
-- call it "weak" (resource uses loadstring/dofile/loadfile, or has compiled scripts we cannot analyze).
local function isCertain(kind, src)
    if kind == "unknown-source" then
        if type(src) ~= "string" then return false end
        if src == "?" or src == "=?" then return false end
        if baseline.calls.loadstring or baseline.calls.dofile or baseline.calls.loadfile then return false end
        if baseline.compiled and not baseline.strict then return false end
        return not sourceKnown(src)
    end
    -- trigger-not-in-resource / function-not-in-resource / loadstring-not-in-resource:
    -- the canary already proved the trigger/function is unknown to this resource's static baseline;
    -- only compiled scripts (unanalyzable code) can make that verdict uncertain.
    return not baseline.compiled
end

local function wrap(fnName)
    local original = _G[fnName]
    if type(original) ~= "function" then return end
    originals[fnName] = original
    _G[fnName] = function(...)
        counts[fnName] = (counts[fnName] or 0) + 1
        if baseline then
            local name = nil
            if NAMED[fnName] then
                local first = (...)
                if type(first) == "string" then name = first end
            end
            local src  = callerSource()
            local kind = nil
            if not sourceKnown(src) then
                kind = "unknown-source"
            elseif fnName == "loadstring" and not baseline.calls.loadstring then
                kind = "loadstring-not-in-resource"
            elseif name and (fnName == "triggerServerEvent" or fnName == "triggerLatentServerEvent")
                and not baseline.triggers[name] and baseline.dynamic == 0 then
                kind = "trigger-not-in-resource"
            elseif not baseline.calls[fnName] then
                kind = "function-not-in-resource"
            end
            if kind then
                local blocked = baseline.block and isCertain(kind, src)
                if blocked and type(rawOutputDebug) == "function" then
                    rawOutputDebug(string.format("[SentinelAC] BLOCKED injected %s in %s (caller: %s, kind: %s)",
                        fnName, RESOURCE, tostring(src), kind))
                end
                report(kind, fnName, name, src, blocked)
                if blocked then
                    -- the injected call never reaches the original function: the event/code is dead
                    if fnName == "loadstring" then return nil end
                    return false
                end
            end
        end
        return original(...)
    end
end

local function hello()
    if acAvailable() then
        rawTrigger("SentinelAC:server:canaryHello", localPlayer, RESOURCE)
    end
end

addEvent("SentinelAC:canary:baseline", true)
addEventHandler("SentinelAC:canary:baseline", root, function(resName, data)
    if resName ~= RESOURCE or type(data) ~= "table" then return end
    local files = {}
    if type(data.files) == "table" then
        for _, f in ipairs(data.files) do files[#files + 1] = normalise(f) end
    end
    files[#files + 1] = normalise(CANARY_FILE)
    baseline = {
        files    = files,
        triggers = type(data.triggers) == "table" and data.triggers or {},
        calls    = type(data.calls) == "table" and data.calls or {},
        dynamic  = tonumber(data.dynamic) or 0,
        compiled = data.compiled == true,
        strict   = data.strict == true,
        block    = data.block == true,
    }
end)

addEventHandler("onClientResourceStart", resourceRoot, function()
    hello()
    if flushTimer and rawIsTimer(flushTimer) then rawKillTimer(flushTimer) end
    flushTimer = rawSetTimer(function()
        if not baseline then hello() end
        flush()
    end, HEARTBEAT, 0)
end)

addEventHandler("onClientResourceStop", resourceRoot, function()
    if flushTimer and rawIsTimer(flushTimer) then rawKillTimer(flushTimer) end
    flushTimer = nil
end)

-- wrap last so that everything above used the original functions
for _, fnName in ipairs(WRAP) do
    wrap(fnName)
end
